---
- name: Creating Hello World Page
  copy:
    content: |
      <html>
      <head>
      <title>Hello World</title>
      </head>
      <body>
      <h1>Hello World!</h1>
      </body>
      </html>
    dest: /var/www/html/index.html
    mode: 0644
