---
# tasks file for apache
- name: install apache 2.4
  yum:
    name: httpd24
    state: present
- name: Enable Allow Override All in httpdconf
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: "AllowOverride None"
    replace: "AllowOverride All"
- name: restart apache service
  service:
    name: httpd
    state: restarted
    enabled: yes
- name: Create Hello World Page on the launched instance
  copy:
    content: |
      <html>
      <head>
      <title>Hello World</title>
      </head>
      <body>
      <h1>Hello World!</h1>
      </body>
      </html>
    dest: /var/www/html/index.html
    mode: 0644
