---
- name: Privisioning EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false
  user: root
  pre_tasks:
    - include_vars: vars/variables.yml
  tasks:
    - name: running another playbook
      include: ec2_scg_playbook.yml

    - name: Create an EC2 key
      ec2_key:
        name: "{{ ec2_keypair }}" 
        region: "{{ ec2_region }}"
      register: ec2_key

    - name: save private key
      copy: content="{{ ec2_key.key.private_key }}" dest="~/.ssh/aws-{{ env }}-private.pem" mode=0600
      when: ec2_key.changed

    - name: load pem files 
      shell: ssh-add {{item}} 
      with_fileglob:
        - "~/.ssh/*.pem"

    - name: Provisioning {{ ec2_count }} instance(s)
      local_action:
        module: ec2
        key_name: "{{ ec2_keypair }}"
        group_id: "{{ sec_grp.group_id }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        vpc_subnet_id: "{{ ec2_subnet_id }}"
        instance_profile_name: "{{ iam_role }}"
        region: "{{ ec2_region }}"
        instance_tags: '{"Type":"{{ec2_instance_type}}", "Name":"{{ec2_tag_Name}}"}'
        assign_public_ip: yes
        wait: true
        exact_count: "{{ ec2_count }}"
        count_tag:
          Role: "{{ ec2_tag_Role }}"
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: "{{ ec2_volume_size }}"
            delete_on_termination: true
      register: ec2

    - name: Adding Server IP Address to the Hosts Group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for the instances to boot by checking the ssh port
      wait_for: host={{item.public_ip}} port=22 delay=15 timeout=300 state=started
      with_items: "{{ ec2.instances }}"

  post_tasks:
    - name: refresh hosts inventory list
      meta: refresh_inventory

- name: Installing Apache Webserver
  hosts: launched
#  become: true
#  become_method: sudo
#  gather_facts: false
  sudo: yes
  roles:
    - apache
...

